export const LIVROS = [
  { id: '01-mateus', nome: 'Mateus', capitulos: 28 },
  { id: '02-marcos', nome: 'Marcos', capitulos: 16 },
  { id: '03-lucas', nome: 'Lucas', capitulos: 24 },
  { id: '04-joao', nome: 'João', capitulos: 21 },
  { id: '05-atos', nome: 'Atos dos Apóstolos', capitulos: 28 },
  { id: '06-romanos', nome: 'Romanos', capitulos: 16 },
  { id: '07-1-corintios', nome: '1 Coríntios', capitulos: 16 },
  { id: '08-2-corintios', nome: '2 Coríntios', capitulos: 13 },
  { id: '09-galatas', nome: 'Gálatas', capitulos: 6 },
  { id: '10-efesios', nome: 'Efésios', capitulos: 6 },
  { id: '11-filipenses', nome: 'Filipenses', capitulos: 4 },
  { id: '12-colossenses', nome: 'Colossenses', capitulos: 4 },
  { id: '13-1-tessalonicenses', nome: '1 Tessalonicenses', capitulos: 5 },
  { id: '14-2-tessalonicenses', nome: '2 Tessalonicenses', capitulos: 3 },
  { id: '15-1-timoteo', nome: '1 Timóteo', capitulos: 6 },
  { id: '16-2-timoteo', nome: '2 Timóteo', capitulos: 4 },
  { id: '17-tito', nome: 'Tito', capitulos: 3 },
  { id: '18-filemom', nome: 'Filemom', capitulos: 1 },
  { id: '19-hebreus', nome: 'Hebreus', capitulos: 13 },
  { id: '20-tiago', nome: 'Tiago', capitulos: 5 },
  { id: '21-1-pedro', nome: '1 Pedro', capitulos: 5 },
  { id: '22-2-pedro', nome: '2 Pedro', capitulos: 3 },
  { id: '23-1-joao', nome: '1 João', capitulos: 5 },
  { id: '24-2-joao', nome: '2 João', capitulos: 1 },
  { id: '25-3-joao', nome: '3 João', capitulos: 1 },
  { id: '26-judas', nome: 'Judas', capitulos: 1 },
  { id: '27-apocalipse', nome: 'Apocalipse', capitulos: 22 },
]
